# Exported from Render on 2026-08-11T13:47:50Z
version: "1"
services:
- type: web
  name: foxv-site
  runtime: static
  repo: https://github.com/SPFT-section/foxv
  staticPublishPath: .
  routes:
  - type: rewrite
    source: /*
    destination: /index.html
  headers:
  - path: /sw.js
    name: Cache-Control
    value: no-cache
  autoDeployTrigger: commit
  rootDir: public
databases:
- name: foxv-db
  databaseName: foxv_db_jvba
  user: foxv_db_jvba_user
  plan: free
  region: oregon
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "18"
